name: Build OpenCOLLADA for Android

on:
  push:
    paths-ignore:
      - 'README.md'
      - '**/*.md'

jobs:
  build-opencollada:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: echo hello